In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\ANIKET\Downloads\Facebook Metrics of Cosmetic Brand.csv")

In [3]:
df.head()

,Unnamed: 0,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 20 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Unnamed: 0                                                           500 non-null    int64
 1   Page total likes                                                     500 non-null    int64
 2   Type                                                                 500 non-null    object
 3   Category                                                             500 non-null    int64
 4   Post Month                                                           500 non-null    int64
 5   Post Weekday                                                         500 non-null    int64
 6   Post Hour                                                            500 non-null    int64
 7   Paid                                                                 499 non-null    float64
 8   Lifetime Post Total Reach                                            500 non-null    int64
 9   Lifetime Post Total Impressions                                      500 non-null    int64
 10  Lifetime Engaged Users                                               500 non-null    int64
 11  Lifetime Post Consumers                                              500 non-null    int64
 12  Lifetime Post Consumptions                                           500 non-null    int64
 13  Lifetime Post Impressions by people who have liked your Page         500 non-null    int64
 14  Lifetime Post reach by people who like your Page                     500 non-null    int64
 15  Lifetime People who have liked your Page and engaged with your post  500 non-null    int64
 16  comment                                                              500 non-null    int64
 17  like                                                                 499 non-null    float64
 18  share                                                                496 non-null    float64
 19  Total Interactions                                                   500 non-null    int64
dtypes: float64(3), int64(16), object(1)
memory usage: 78.3+ KB

In [5]:
df.isnull()

,Unnamed: 0,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False

In [6]:
df.dropna(how='any',axis=0)

,Unnamed: 0,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,494,85093,Photo,3,1,7,10,0.0,5400,9218,810,756,1003,5654,3230,422,10,125.0,41.0,176
495,495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136

In [7]:
df1=df.loc[1:245,['Category','Lifetime Post Total Reach','Type','Total Interactions']]

In [8]:
df2=df.loc[245:500,['Post Month','Post Weekday','Post Hour','Lifetime Post Consumers']]

In [9]:
df1

     Category  Lifetime Post Total Reach    Type  Total Interactions
1           2                      10460  Status                 164
2           3                       2413   Photo                  80
3           2                      50128   Photo                1777
4           2                       7244   Photo                 393
5           2                      10472  Status                 186
..        ...                        ...     ...                 ...
241         1                       4892   Photo                 144
242         2                      17360  Status                 572
243         1                      21872   Video                 409
244         2                     180480   Photo                6334
245         1                      44464   Photo                 188

[245 rows x 4 columns]

In [10]:
df2

     Post Month  Post Weekday  Post Hour  Lifetime Post Consumers
245           7             2         13                      930
246           7             2          8                      503
247           7             1         12                      482
248           7             1          6                      512
249           7             7         11                      444
..          ...           ...        ...                      ...
495           1             7          2                      708
496           1             5          8                      508
497           1             5          2                      572
498           1             4         11                      574
499           1             4          4                      524

[255 rows x 4 columns]

In [11]:
df_row = pd.concat([df1, df2])

In [12]:
df_row

,Category,Lifetime Post Total Reach,Type,Total Interactions,Post Month,Post Weekday,Post Hour,Lifetime Post Consumers
1,2.0,10460.0,Status,164.0,NaN,NaN,NaN,NaN
2,3.0,2413.0,Photo,80.0,NaN,NaN,NaN,NaN
3,2.0,50128.0,Photo,1777.0,NaN,NaN,NaN,NaN
4,2.0,7244.0,Photo,393.0,NaN,NaN,NaN,NaN
5,2.0,10472.0,Status,186.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
495,NaN,NaN,NaN,NaN,1.0,7.0,2.0,708.0
496,NaN,NaN,NaN,NaN,1.0,5.0,8.0,508.0
497,NaN,NaN,NaN,NaN,1.0,5.0,2.0,572.0
498,NaN,NaN,NaN,NaN,1.0,4.0,11.0,574.0
499,NaN,NaN,NaN,NaN,1.0,4.0,4.0,524.0

In [13]:
df.shape

(500, 20)

In [14]:
df.melt()

                variable value
0             Unnamed: 0     0
1             Unnamed: 0     1
2             Unnamed: 0     2
3             Unnamed: 0     3
4             Unnamed: 0     4
...                  ...   ...
9995  Total Interactions    84
9996  Total Interactions    75
9997  Total Interactions   115
9998  Total Interactions   136
9999  Total Interactions   119

[10000 rows x 2 columns]

In [15]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
Unnamed: 0,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441,...,85979,85979,85979,85093,85093,85093,81370,81370,81370,81370
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Link,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,2,3,2,2,2,3,3,2,3,...,3,3,1,3,3,3,2,1,3,2
Post Month,12,12,12,12,12,12,12,12,12,12,...,1,1,1,1,1,1,1,1,1,1
Post Weekday,4,3,3,2,2,1,1,7,7,6,...,6,6,5,1,7,7,5,5,4,4
Post Hour,3,10,3,10,3,9,3,9,3,10,...,11,3,11,2,10,2,8,2,11,4
Paid,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
Lifetime Post Total Reach,2752,10460,2413,50128,7244,10472,11692,13720,11844,4694,...,5280,6184,45920,8412,5400,4684,3480,3778,4156,4188
Lifetime Post Total Impressions,5091,19057,4373,87991,13594,20849,19479,24137,22538,8668,...,8703,10228,5808,13960,9218,7536,6229,7216,7564,7292
Lifetime Engaged Users,178,1457,177,2211,671,1191,481,537,1530,280,...,951,956,753,1179,810,733,537,625,626,564
Lifetime Post Consumers,109,1361,113,790,410,1073,265,232,1407,183,...,911,901,655,1111,756,708,508,572,574,524
Lifetime Post Consumptions,159,1674,154,1119,580,1389,364,305,1692,250,...,1237,1140,763,1632,1003,985,687,795,832,743
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228,16034,15432,19728,15220,4309,...,5757,6085,15766,8632,5654,4750,3961,4742,4534,3861
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200,7852,9328,11056,7912,2324,...,3300,3502,10720,5348,3230,2876,2104,2388,2452,2200
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396,1016,379,422,1250,199,...,431,437,220,699,422,392,301,363,370,316
comment,4,5,0,58,19,1,3,0,0,3,...,1,1,0,17,10,5,0,4,7,0
like,79.0,130.0,66.0,1572.0,325.0,152.0,249.0,325.0,161.0,113.0,...,79.0,105.0,128.0,185.0,125.0,53.0,53.0,93.0,91.0,91.0
share,17.0,29.0,14.0,147.0,49.0,33.0,27.0,14.0,31.0,26.0,...,30.0,46.0,9.0,55.0,41.0,26.0,22.0,18.0,38.0,28.0
Total Interactions,100,164,80,1777,393,186,279,339,192,142,...,110,152,137,257,176,84,75,115,136,119

In [16]:
df1.transpose()

,1,2,3,4,5,6,7,8,9,10,...,236,237,238,239,240,241,242,243,244,245
Category,2,3,2,2,2,3,3,2,3,2,...,3,2,1,2,3,1,2,1,2,1
Lifetime Post Total Reach,10460,2413,50128,7244,10472,11692,13720,11844,4694,21744,...,10888,3594,3384,4096,19968,4892,17360,21872,180480,44464
Type,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,Status,...,Photo,Photo,Photo,Photo,Photo,Photo,Status,Video,Photo,Photo
Total Interactions,164,80,1777,393,186,279,339,192,142,252,...,294,139,128,186,624,144,572,409,6334,188

In [17]:
df2.transpose()

,245,246,247,248,249,250,251,252,253,254,...,490,491,492,493,494,495,496,497,498,499
Post Month,7,7,7,7,7,7,7,7,7,7,...,1,1,1,1,1,1,1,1,1,1
Post Weekday,2,2,1,1,7,7,6,6,5,5,...,6,6,5,1,7,7,5,5,4,4
Post Hour,13,8,12,6,11,6,11,5,12,3,...,11,3,11,2,10,2,8,2,11,4
Lifetime Post Consumers,930,503,482,512,444,570,740,646,2327,963,...,911,901,655,1111,756,708,508,572,574,524

In [18]:
df.sort_values(by='Category')

,Unnamed: 0,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
497,497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
17,17,138414,Photo,1,12,2,12,1.0,53264,111785,1706,1103,1655,92512,39776,1307,15,678.0,20.0,713
21,21,138414,Photo,1,12,7,10,0.0,1384,2467,15,15,20,2196,1172,15,0,0.0,0.0,0
22,22,138414,Link,1,12,7,10,0.0,3454,6853,118,104,130,6282,3100,106,0,16.0,2.0,18
29,29,138895,Video,1,12,4,11,1.0,36208,61262,1141,1068,1728,30131,14112,559,18,143.0,13.0,174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18,18,138414,Status,3,12,2,3,0.0,3930,7509,130,86,112,5009,2410,101,4,54.0,17.0,75
498,498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
493,493,85093,Photo,3,1,1,2,0.0,8412,13960,1179,1111,1632,8632,5348,699,17,185.0,55.0,257
494,494,85093,Photo,3,1,7,10,0.0,5400,9218,810,756,1003,5654,3230,422,10,125.0,41.0,176
495,495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84

In [19]:
df.sort_index()

,Unnamed: 0,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119